# Generated by Django 5.0.6 on 2024-05-19 11:33

import django.db.models.deletion
import product.helps
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=product.helps.SaveMediaFiles.category_image_path)),
                ('name', models.CharField(max_length=50)),
                ('product_count', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['id'], name='product_cat_id_37f831_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=product.helps.SaveMediaFiles.product_image_path)),
                ('name', models.CharField(max_length=25)),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('price', models.IntegerField()),
                ('price_type', models.CharField(choices=[('EURO', 'EURO'), ('$', '$'), ('SO`M', 'SO`M')], max_length=4)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ClientComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=product.helps.SaveMediaFiles.clientcomment_image_path)),
                ('name', models.CharField(max_length=150)),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['id'], name='product_use_id_0c9bc7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id'], name='product_pro_id_06b227_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcomment',
            index=models.Index(fields=['id'], name='product_cli_id_2a2a4e_idx'),
        ),
    ]
